"""fix_stopped_by_risk_constraint

Revision ID: 6d66c529e2e7
Revises: f998822e456f
Create Date: 2026-01-26 13:51:38.323614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect, text


# revision identifiers, used by Alembic.
revision: str = '6d66c529e2e7'
down_revision: Union[str, None] = 'f998822e456f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Make migration idempotent: check for existing objects BEFORE modifying them
    from sqlalchemy import inspect
    
    bind = op.get_bind()
    inspector = inspect(bind)
    
    # Get existing tables first
    existing_tables = inspector.get_table_names()
    
    # Helper to get indexes for a table (returns empty list if table doesn't exist)
    def get_table_indexes(table_name):
        if table_name not in existing_tables:
            return []
        try:
            return [idx['name'] for idx in inspector.get_indexes(table_name)]
        except Exception:
            return []
    
    # Helper to get constraints for a table
    def get_table_constraints(table_name):
        if table_name not in existing_tables:
            return []
        try:
            return [c['name'] for c in inspector.get_unique_constraints(table_name)]
        except Exception:
            return []
    
    op.create_index(op.f('ix_completed_trade_orders_account_id'), 'completed_trade_orders', ['account_id'], unique=False)
    op.create_index(op.f('ix_completed_trade_orders_completed_trade_id'), 'completed_trade_orders', ['completed_trade_id'], unique=False)
    op.create_index(op.f('ix_completed_trade_orders_order_id'), 'completed_trade_orders', ['order_id'], unique=False)
    op.create_index(op.f('ix_completed_trade_orders_timestamp'), 'completed_trade_orders', ['timestamp'], unique=False)
    op.create_index(op.f('ix_completed_trade_orders_trade_id'), 'completed_trade_orders', ['trade_id'], unique=False)
    
    # Check if indexes exist before dropping (idempotent migration)
    completed_trades_indexes = get_table_indexes('completed_trades')
    if 'idx_completed_trades_close_event_id' in completed_trades_indexes:
        op.drop_index(op.f('idx_completed_trades_close_event_id'), table_name='completed_trades')
    if 'idx_completed_trades_entry_order_id' in completed_trades_indexes:
        op.drop_index(op.f('idx_completed_trades_entry_order_id'), table_name='completed_trades')
    if 'idx_completed_trades_entry_time' in completed_trades_indexes:
        op.drop_index(op.f('idx_completed_trades_entry_time'), table_name='completed_trades')
    if 'idx_completed_trades_exit_order_id' in completed_trades_indexes:
        op.drop_index(op.f('idx_completed_trades_exit_order_id'), table_name='completed_trades')
    if 'idx_completed_trades_strategy_id' in completed_trades_indexes:
        op.drop_index(op.f('idx_completed_trades_strategy_id'), table_name='completed_trades')
    if 'idx_completed_trades_user_id' in completed_trades_indexes:
        op.drop_index(op.f('idx_completed_trades_user_id'), table_name='completed_trades')
    op.create_index(op.f('ix_completed_trades_account_id'), 'completed_trades', ['account_id'], unique=False)
    op.create_index(op.f('ix_completed_trades_close_event_id'), 'completed_trades', ['close_event_id'], unique=True)
    op.create_index(op.f('ix_completed_trades_entry_order_id'), 'completed_trades', ['entry_order_id'], unique=False)
    op.create_index(op.f('ix_completed_trades_entry_time'), 'completed_trades', ['entry_time'], unique=False)
    op.create_index(op.f('ix_completed_trades_exit_order_id'), 'completed_trades', ['exit_order_id'], unique=False)
    op.create_index(op.f('ix_completed_trades_exit_time'), 'completed_trades', ['exit_time'], unique=False)
    op.create_index(op.f('ix_completed_trades_position_instance_id'), 'completed_trades', ['position_instance_id'], unique=False)
    op.create_index(op.f('ix_completed_trades_strategy_id'), 'completed_trades', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_completed_trades_symbol'), 'completed_trades', ['symbol'], unique=False)
    op.create_index(op.f('ix_completed_trades_user_id'), 'completed_trades', ['user_id'], unique=False)
    op.create_index(op.f('ix_strategies_position_instance_id'), 'strategies', ['position_instance_id'], unique=False)
    
    # Check if index exists before dropping (idempotent migration)
    # Drop old index if it exists, then create new one
    strategy_metrics_indexes = get_table_indexes('strategy_metrics')
    if 'idx_strategy_metrics_period_type' in strategy_metrics_indexes:
        try:
            op.drop_index(op.f('idx_strategy_metrics_period_type'), table_name='strategy_metrics')
        except Exception:
            pass  # Index might have different definition or already dropped
    # Create the new index (idempotent - will fail gracefully if already exists with same definition)
    try:
        op.create_index('idx_strategy_metrics_period_type', 'strategy_metrics', ['period_type', 'period_start'], unique=False, postgresql_ops={'period_start': 'DESC'})
    except Exception:
        pass  # Index might already exist with correct definition
    # Check if constraint exists before dropping
    strategy_risk_config_constraints = get_table_constraints('strategy_risk_config')
    if 'strategy_risk_config_strategy_id_unique' in strategy_risk_config_constraints:
        try:
            op.drop_constraint(op.f('strategy_risk_config_strategy_id_unique'), 'strategy_risk_config', type_='unique')
        except Exception:
            pass  # Constraint might not exist
    op.create_index(op.f('ix_strategy_risk_config_strategy_id'), 'strategy_risk_config', ['strategy_id'], unique=True)
    op.create_index(op.f('ix_strategy_risk_config_user_id'), 'strategy_risk_config', ['user_id'], unique=False)
    
    # Check if indexes exist before dropping (idempotent)
    trades_indexes = get_table_indexes('trades')
    if 'idx_trades_strategy_timestamp' in trades_indexes:
        try:
            op.drop_index(op.f('idx_trades_strategy_timestamp'), table_name='trades')
        except Exception:
            pass
    try:
        op.create_index('idx_trades_strategy_timestamp', 'trades', ['strategy_id', 'timestamp'], unique=False, postgresql_ops={'timestamp': 'DESC'})
    except Exception:
        pass  # Index might already exist
    
    if 'idx_trades_user_timestamp' in trades_indexes:
        try:
            op.drop_index(op.f('idx_trades_user_timestamp'), table_name='trades')
        except Exception:
            pass
    try:
        op.create_index('idx_trades_user_timestamp', 'trades', ['user_id', 'timestamp'], unique=False, postgresql_ops={'timestamp': 'DESC'})
    except Exception:
        pass  # Index might already exist
    
    try:
        op.create_index(op.f('ix_trades_position_instance_id'), 'trades', ['position_instance_id'], unique=False)
    except Exception:
        pass  # Index might already exist
    
    wf_indexes = get_table_indexes('walk_forward_analyses')
    if 'idx_wf_analyses_created_at' in wf_indexes:
        try:
            op.drop_index(op.f('idx_wf_analyses_created_at'), table_name='walk_forward_analyses')
        except Exception:
            pass
    try:
        op.create_index('idx_wf_analyses_created_at', 'walk_forward_analyses', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    except Exception:
        pass  # Index might already exist
    
    # Fix strategies status constraint: change 'paused_by_risk' to 'stopped_by_risk'
    # Try to drop existing constraint (idempotent - ignore if doesn't exist)
    try:
        op.drop_constraint('strategies_status_check', 'strategies', type_='check')
    except Exception:
        pass  # Constraint might not exist, which is fine
    op.create_check_constraint(
        'strategies_status_check',
        'strategies',
        "status IN ('stopped', 'running', 'error', 'stopped_by_risk')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_wf_analyses_created_at', table_name='walk_forward_analyses', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_wf_analyses_created_at'), 'walk_forward_analyses', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_trades_position_instance_id'), table_name='trades')
    op.drop_index('idx_trades_user_timestamp', table_name='trades', postgresql_ops={'timestamp': 'DESC'})
    op.create_index(op.f('idx_trades_user_timestamp'), 'trades', ['user_id', sa.literal_column('timestamp DESC')], unique=False)
    op.drop_index('idx_trades_strategy_timestamp', table_name='trades', postgresql_ops={'timestamp': 'DESC'})
    op.create_index(op.f('idx_trades_strategy_timestamp'), 'trades', ['strategy_id', sa.literal_column('timestamp DESC')], unique=False)
    op.drop_index(op.f('ix_strategy_risk_config_user_id'), table_name='strategy_risk_config')
    op.drop_index(op.f('ix_strategy_risk_config_strategy_id'), table_name='strategy_risk_config')
    op.create_unique_constraint(op.f('strategy_risk_config_strategy_id_unique'), 'strategy_risk_config', ['strategy_id'], postgresql_nulls_not_distinct=False)
    op.drop_index('idx_strategy_metrics_period_type', table_name='strategy_metrics', postgresql_ops={'period_start': 'DESC'})
    op.create_index(op.f('idx_strategy_metrics_period_type'), 'strategy_metrics', ['period_type', sa.literal_column('period_start DESC')], unique=False)
    op.drop_index(op.f('ix_strategies_position_instance_id'), table_name='strategies')
    op.drop_index(op.f('ix_completed_trades_user_id'), table_name='completed_trades')
    op.drop_index(op.f('ix_completed_trades_symbol'), table_name='completed_trades')
    op.drop_index(op.f('ix_completed_trades_strategy_id'), table_name='completed_trades')
    op.drop_index(op.f('ix_completed_trades_position_instance_id'), table_name='completed_trades')
    op.drop_index(op.f('ix_completed_trades_exit_time'), table_name='completed_trades')
    op.drop_index(op.f('ix_completed_trades_exit_order_id'), table_name='completed_trades')
    op.drop_index(op.f('ix_completed_trades_entry_time'), table_name='completed_trades')
    op.drop_index(op.f('ix_completed_trades_entry_order_id'), table_name='completed_trades')
    op.drop_index(op.f('ix_completed_trades_close_event_id'), table_name='completed_trades')
    op.drop_index(op.f('ix_completed_trades_account_id'), table_name='completed_trades')
    op.create_index(op.f('idx_completed_trades_user_id'), 'completed_trades', ['user_id'], unique=False)
    op.create_index(op.f('idx_completed_trades_strategy_id'), 'completed_trades', ['strategy_id'], unique=False)
    op.create_index(op.f('idx_completed_trades_exit_order_id'), 'completed_trades', ['exit_order_id'], unique=False)
    op.create_index(op.f('idx_completed_trades_entry_time'), 'completed_trades', ['entry_time'], unique=False)
    op.create_index(op.f('idx_completed_trades_entry_order_id'), 'completed_trades', ['entry_order_id'], unique=False)
    op.create_index(op.f('idx_completed_trades_close_event_id'), 'completed_trades', ['close_event_id'], unique=True)
    op.drop_index(op.f('ix_completed_trade_orders_trade_id'), table_name='completed_trade_orders')
    op.drop_index(op.f('ix_completed_trade_orders_timestamp'), table_name='completed_trade_orders')
    op.drop_index(op.f('ix_completed_trade_orders_order_id'), table_name='completed_trade_orders')
    op.drop_index(op.f('ix_completed_trade_orders_completed_trade_id'), table_name='completed_trade_orders')
    op.drop_index(op.f('ix_completed_trade_orders_account_id'), table_name='completed_trade_orders')
    
    # Revert strategies status constraint: change 'stopped_by_risk' back to 'paused_by_risk'
    op.drop_constraint('strategies_status_check', 'strategies', type_='check')
    op.create_check_constraint(
        'strategies_status_check',
        'strategies',
        "status IN ('stopped', 'running', 'error', 'paused_by_risk')"
    )
    # ### end Alembic commands ###

