"""fix_stopped_by_risk_constraint

Revision ID: 6d66c529e2e7
Revises: f998822e456f
Create Date: 2026-01-26 13:51:38.323614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d66c529e2e7'
down_revision: Union[str, None] = 'f998822e456f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_completed_trade_orders_account_id'), 'completed_trade_orders', ['account_id'], unique=False)
    op.create_index(op.f('ix_completed_trade_orders_completed_trade_id'), 'completed_trade_orders', ['completed_trade_id'], unique=False)
    op.create_index(op.f('ix_completed_trade_orders_order_id'), 'completed_trade_orders', ['order_id'], unique=False)
    op.create_index(op.f('ix_completed_trade_orders_timestamp'), 'completed_trade_orders', ['timestamp'], unique=False)
    op.create_index(op.f('ix_completed_trade_orders_trade_id'), 'completed_trade_orders', ['trade_id'], unique=False)
    op.drop_index(op.f('idx_completed_trades_close_event_id'), table_name='completed_trades')
    op.drop_index(op.f('idx_completed_trades_entry_order_id'), table_name='completed_trades')
    op.drop_index(op.f('idx_completed_trades_entry_time'), table_name='completed_trades')
    op.drop_index(op.f('idx_completed_trades_exit_order_id'), table_name='completed_trades')
    op.drop_index(op.f('idx_completed_trades_strategy_id'), table_name='completed_trades')
    op.drop_index(op.f('idx_completed_trades_user_id'), table_name='completed_trades')
    op.create_index(op.f('ix_completed_trades_account_id'), 'completed_trades', ['account_id'], unique=False)
    op.create_index(op.f('ix_completed_trades_close_event_id'), 'completed_trades', ['close_event_id'], unique=True)
    op.create_index(op.f('ix_completed_trades_entry_order_id'), 'completed_trades', ['entry_order_id'], unique=False)
    op.create_index(op.f('ix_completed_trades_entry_time'), 'completed_trades', ['entry_time'], unique=False)
    op.create_index(op.f('ix_completed_trades_exit_order_id'), 'completed_trades', ['exit_order_id'], unique=False)
    op.create_index(op.f('ix_completed_trades_exit_time'), 'completed_trades', ['exit_time'], unique=False)
    op.create_index(op.f('ix_completed_trades_position_instance_id'), 'completed_trades', ['position_instance_id'], unique=False)
    op.create_index(op.f('ix_completed_trades_strategy_id'), 'completed_trades', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_completed_trades_symbol'), 'completed_trades', ['symbol'], unique=False)
    op.create_index(op.f('ix_completed_trades_user_id'), 'completed_trades', ['user_id'], unique=False)
    op.create_index(op.f('ix_strategies_position_instance_id'), 'strategies', ['position_instance_id'], unique=False)
    op.drop_index(op.f('idx_strategy_metrics_period_type'), table_name='strategy_metrics')
    op.create_index('idx_strategy_metrics_period_type', 'strategy_metrics', ['period_type', 'period_start'], unique=False, postgresql_ops={'period_start': 'DESC'})
    op.drop_constraint(op.f('strategy_risk_config_strategy_id_unique'), 'strategy_risk_config', type_='unique')
    op.create_index(op.f('ix_strategy_risk_config_strategy_id'), 'strategy_risk_config', ['strategy_id'], unique=True)
    op.create_index(op.f('ix_strategy_risk_config_user_id'), 'strategy_risk_config', ['user_id'], unique=False)
    op.drop_index(op.f('idx_trades_strategy_timestamp'), table_name='trades')
    op.create_index('idx_trades_strategy_timestamp', 'trades', ['strategy_id', 'timestamp'], unique=False, postgresql_ops={'timestamp': 'DESC'})
    op.drop_index(op.f('idx_trades_user_timestamp'), table_name='trades')
    op.create_index('idx_trades_user_timestamp', 'trades', ['user_id', 'timestamp'], unique=False, postgresql_ops={'timestamp': 'DESC'})
    op.create_index(op.f('ix_trades_position_instance_id'), 'trades', ['position_instance_id'], unique=False)
    op.drop_index(op.f('idx_wf_analyses_created_at'), table_name='walk_forward_analyses')
    op.create_index('idx_wf_analyses_created_at', 'walk_forward_analyses', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    
    # Fix strategies status constraint: change 'paused_by_risk' to 'stopped_by_risk'
    op.drop_constraint('strategies_status_check', 'strategies', type_='check')
    op.create_check_constraint(
        'strategies_status_check',
        'strategies',
        "status IN ('stopped', 'running', 'error', 'stopped_by_risk')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_wf_analyses_created_at', table_name='walk_forward_analyses', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_wf_analyses_created_at'), 'walk_forward_analyses', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_trades_position_instance_id'), table_name='trades')
    op.drop_index('idx_trades_user_timestamp', table_name='trades', postgresql_ops={'timestamp': 'DESC'})
    op.create_index(op.f('idx_trades_user_timestamp'), 'trades', ['user_id', sa.literal_column('timestamp DESC')], unique=False)
    op.drop_index('idx_trades_strategy_timestamp', table_name='trades', postgresql_ops={'timestamp': 'DESC'})
    op.create_index(op.f('idx_trades_strategy_timestamp'), 'trades', ['strategy_id', sa.literal_column('timestamp DESC')], unique=False)
    op.drop_index(op.f('ix_strategy_risk_config_user_id'), table_name='strategy_risk_config')
    op.drop_index(op.f('ix_strategy_risk_config_strategy_id'), table_name='strategy_risk_config')
    op.create_unique_constraint(op.f('strategy_risk_config_strategy_id_unique'), 'strategy_risk_config', ['strategy_id'], postgresql_nulls_not_distinct=False)
    op.drop_index('idx_strategy_metrics_period_type', table_name='strategy_metrics', postgresql_ops={'period_start': 'DESC'})
    op.create_index(op.f('idx_strategy_metrics_period_type'), 'strategy_metrics', ['period_type', sa.literal_column('period_start DESC')], unique=False)
    op.drop_index(op.f('ix_strategies_position_instance_id'), table_name='strategies')
    op.drop_index(op.f('ix_completed_trades_user_id'), table_name='completed_trades')
    op.drop_index(op.f('ix_completed_trades_symbol'), table_name='completed_trades')
    op.drop_index(op.f('ix_completed_trades_strategy_id'), table_name='completed_trades')
    op.drop_index(op.f('ix_completed_trades_position_instance_id'), table_name='completed_trades')
    op.drop_index(op.f('ix_completed_trades_exit_time'), table_name='completed_trades')
    op.drop_index(op.f('ix_completed_trades_exit_order_id'), table_name='completed_trades')
    op.drop_index(op.f('ix_completed_trades_entry_time'), table_name='completed_trades')
    op.drop_index(op.f('ix_completed_trades_entry_order_id'), table_name='completed_trades')
    op.drop_index(op.f('ix_completed_trades_close_event_id'), table_name='completed_trades')
    op.drop_index(op.f('ix_completed_trades_account_id'), table_name='completed_trades')
    op.create_index(op.f('idx_completed_trades_user_id'), 'completed_trades', ['user_id'], unique=False)
    op.create_index(op.f('idx_completed_trades_strategy_id'), 'completed_trades', ['strategy_id'], unique=False)
    op.create_index(op.f('idx_completed_trades_exit_order_id'), 'completed_trades', ['exit_order_id'], unique=False)
    op.create_index(op.f('idx_completed_trades_entry_time'), 'completed_trades', ['entry_time'], unique=False)
    op.create_index(op.f('idx_completed_trades_entry_order_id'), 'completed_trades', ['entry_order_id'], unique=False)
    op.create_index(op.f('idx_completed_trades_close_event_id'), 'completed_trades', ['close_event_id'], unique=True)
    op.drop_index(op.f('ix_completed_trade_orders_trade_id'), table_name='completed_trade_orders')
    op.drop_index(op.f('ix_completed_trade_orders_timestamp'), table_name='completed_trade_orders')
    op.drop_index(op.f('ix_completed_trade_orders_order_id'), table_name='completed_trade_orders')
    op.drop_index(op.f('ix_completed_trade_orders_completed_trade_id'), table_name='completed_trade_orders')
    op.drop_index(op.f('ix_completed_trade_orders_account_id'), table_name='completed_trade_orders')
    
    # Revert strategies status constraint: change 'stopped_by_risk' back to 'paused_by_risk'
    op.drop_constraint('strategies_status_check', 'strategies', type_='check')
    op.create_check_constraint(
        'strategies_status_check',
        'strategies',
        "status IN ('stopped', 'running', 'error', 'paused_by_risk')"
    )
    # ### end Alembic commands ###

