"""Initial schema

Revision ID: af03ee2f45dc
Revises: 
Create Date: 2025-12-10 15:18:53.108900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af03ee2f45dc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("name ~ '^[a-z0-9_-]+$'", name='roles_name_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("email ~* '^[A-Za-z0-9._%%+-]+@[A-Za-z0-9.-]+\\.[A-Z|a-z]{2,}$'", name='users_email_check'),
    sa.CheckConstraint("username ~ '^[a-z0-9_-]+$'", name='users_username_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('api_secret_encrypted', sa.Text(), nullable=False),
    sa.Column('testnet', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("account_id ~ '^[a-z0-9_-]+$'", name='accounts_account_id_check'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_accounts_user_account_id', 'accounts', ['user_id', 'account_id'], unique=True)
    op.create_index(op.f('ix_accounts_account_id'), 'accounts', ['account_id'], unique=False)
    op.create_index(op.f('ix_accounts_is_active'), 'accounts', ['is_active'], unique=False)
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    op.create_table('api_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_name', sa.String(length=255), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('token_prefix', sa.String(length=20), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_tokens_created_at'), 'api_tokens', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_tokens_expires_at'), 'api_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_api_tokens_is_active'), 'api_tokens', ['is_active'], unique=False)
    op.create_index(op.f('ix_api_tokens_token_hash'), 'api_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_api_tokens_user_id'), 'api_tokens', ['user_id'], unique=False)
    op.create_table('backtests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('strategy_type', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('leverage', sa.Integer(), nullable=False),
    sa.Column('risk_per_trade', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('initial_balance', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('keep_details', sa.Boolean(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('completed_trades', sa.Integer(), nullable=False),
    sa.Column('winning_trades', sa.Integer(), nullable=False),
    sa.Column('losing_trades', sa.Integer(), nullable=False),
    sa.Column('total_pnl', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('avg_profit_per_trade', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('largest_win', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('largest_loss', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('max_drawdown_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('final_balance', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('roi', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('candles_processed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('leverage >= 1 AND leverage <= 50', name='backtests_leverage_check'),
    sa.CheckConstraint('risk_per_trade > 0 AND risk_per_trade < 1', name='backtests_risk_check'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_backtests_params', 'backtests', ['params'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_backtests_created_at'), 'backtests', ['created_at'], unique=False)
    op.create_index(op.f('ix_backtests_start_time'), 'backtests', ['start_time'], unique=False)
    op.create_index(op.f('ix_backtests_strategy_type'), 'backtests', ['strategy_type'], unique=False)
    op.create_index(op.f('ix_backtests_symbol'), 'backtests', ['symbol'], unique=False)
    op.create_index(op.f('ix_backtests_user_id'), 'backtests', ['user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_index('idx_user_roles_role_id', 'user_roles', ['role_id'], unique=False)
    op.create_index('idx_user_roles_user_id', 'user_roles', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_token', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_created_at'), 'user_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_expires_at'), 'user_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_is_active'), 'user_sessions', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_sessions_session_token'), 'user_sessions', ['session_token'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('backtest_trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('backtest_id', sa.UUID(), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('position_side', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('pnl', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('net_pnl', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('entry_fee', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('exit_fee', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('exit_reason', sa.String(length=50), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("position_side IN ('LONG', 'SHORT')", name='backtest_trades_position_side_check'),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_trades_backtest_id'), 'backtest_trades', ['backtest_id'], unique=False)
    op.create_index(op.f('ix_backtest_trades_entry_time'), 'backtest_trades', ['entry_time'], unique=False)
    op.create_index(op.f('ix_backtest_trades_is_open'), 'backtest_trades', ['is_open'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('strategy_type', sa.String(length=50), nullable=False),
    sa.Column('leverage', sa.Integer(), nullable=False),
    sa.Column('risk_per_trade', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('fixed_amount', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('max_positions', sa.Integer(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_signal', sa.String(length=10), nullable=True),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('position_size', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('position_side', sa.String(length=10), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_trade_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("last_signal IS NULL OR last_signal IN ('BUY', 'SELL', 'HOLD')", name='strategies_last_signal_check'),
    sa.CheckConstraint("position_side IS NULL OR position_side IN ('LONG', 'SHORT')", name='strategies_position_side_check'),
    sa.CheckConstraint("status IN ('stopped', 'running', 'error')", name='strategies_status_check'),
    sa.CheckConstraint('leverage >= 1 AND leverage <= 50', name='strategies_leverage_check'),
    sa.CheckConstraint('max_positions >= 1 AND max_positions <= 5', name='strategies_max_positions_check'),
    sa.CheckConstraint('risk_per_trade > 0 AND risk_per_trade < 1', name='strategies_risk_check'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_strategies_params', 'strategies', ['params'], unique=False, postgresql_using='gin')
    op.create_index('idx_strategies_user_strategy_id', 'strategies', ['user_id', 'strategy_id'], unique=True)
    op.create_index(op.f('ix_strategies_account_id'), 'strategies', ['account_id'], unique=False)
    op.create_index(op.f('ix_strategies_created_at'), 'strategies', ['created_at'], unique=False)
    op.create_index(op.f('ix_strategies_position_side'), 'strategies', ['position_side'], unique=False)
    op.create_index(op.f('ix_strategies_status'), 'strategies', ['status'], unique=False)
    op.create_index(op.f('ix_strategies_strategy_id'), 'strategies', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_strategies_strategy_type'), 'strategies', ['strategy_type'], unique=False)
    op.create_index(op.f('ix_strategies_symbol'), 'strategies', ['symbol'], unique=False)
    op.create_index(op.f('ix_strategies_user_id'), 'strategies', ['user_id'], unique=False)
    op.create_table('strategy_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('completed_trades', sa.Integer(), nullable=False),
    sa.Column('winning_trades', sa.Integer(), nullable=False),
    sa.Column('losing_trades', sa.Integer(), nullable=False),
    sa.Column('total_pnl', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('avg_profit_per_trade', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('largest_win', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('largest_loss', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("period_type IN ('hourly', 'daily', 'weekly', 'monthly')", name='strategy_metrics_period_type_check'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_strategy_metrics_period', 'strategy_metrics', ['period_start', 'period_end'], unique=False)
    op.create_index('idx_strategy_metrics_period_type', 'strategy_metrics', ['period_type', 'period_start'], unique=False, postgresql_ops={'period_start': 'DESC'})
    op.create_index(op.f('ix_strategy_metrics_period_type'), 'strategy_metrics', ['period_type'], unique=False)
    op.create_index(op.f('ix_strategy_metrics_strategy_id'), 'strategy_metrics', ['strategy_id'], unique=False)
    op.create_table('system_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("event_level IN ('INFO', 'WARNING', 'ERROR', 'CRITICAL')", name='system_events_event_level_check'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_events_created_at'), 'system_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_events_event_level'), 'system_events', ['event_level'], unique=False)
    op.create_index(op.f('ix_system_events_event_type'), 'system_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_system_events_strategy_id'), 'system_events', ['strategy_id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('client_order_id', sa.String(length=100), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('avg_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('executed_qty', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('notional_value', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('cummulative_quote_qty', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('initial_margin', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('commission', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('commission_asset', sa.String(length=10), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('position_side', sa.String(length=10), nullable=True),
    sa.Column('leverage', sa.Integer(), nullable=True),
    sa.Column('margin_type', sa.String(length=20), nullable=True),
    sa.Column('exit_reason', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_in_force', sa.String(length=10), nullable=True),
    sa.Column('working_type', sa.String(length=20), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("position_side IS NULL OR position_side IN ('LONG', 'SHORT')", name='trades_position_side_check'),
    sa.CheckConstraint("side IN ('BUY', 'SELL')", name='trades_side_check'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trades_strategy_order_id', 'trades', ['strategy_id', 'order_id'], unique=True)
    op.create_index('idx_trades_strategy_timestamp', 'trades', ['strategy_id', 'timestamp'], unique=False, postgresql_ops={'timestamp': 'DESC'})
    op.create_index('idx_trades_user_timestamp', 'trades', ['user_id', 'timestamp'], unique=False, postgresql_ops={'timestamp': 'DESC'})
    op.create_index(op.f('ix_trades_created_at'), 'trades', ['created_at'], unique=False)
    op.create_index(op.f('ix_trades_exit_reason'), 'trades', ['exit_reason'], unique=False)
    op.create_index(op.f('ix_trades_order_id'), 'trades', ['order_id'], unique=False)
    op.create_index(op.f('ix_trades_position_side'), 'trades', ['position_side'], unique=False)
    op.create_index(op.f('ix_trades_status'), 'trades', ['status'], unique=False)
    op.create_index(op.f('ix_trades_strategy_id'), 'trades', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    op.create_index(op.f('ix_trades_timestamp'), 'trades', ['timestamp'], unique=False)
    op.create_index(op.f('ix_trades_user_id'), 'trades', ['user_id'], unique=False)
    op.create_table('trade_pairs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('entry_trade_id', sa.UUID(), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entry_side', sa.String(length=10), nullable=False),
    sa.Column('position_side', sa.String(length=10), nullable=False),
    sa.Column('exit_trade_id', sa.UUID(), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_reason', sa.String(length=50), nullable=True),
    sa.Column('pnl', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('net_pnl', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('entry_fee', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('exit_fee', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("entry_side IN ('BUY', 'SELL')", name='trade_pairs_entry_side_check'),
    sa.CheckConstraint("position_side IN ('LONG', 'SHORT')", name='trade_pairs_position_side_check'),
    sa.ForeignKeyConstraint(['entry_trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exit_trade_id'], ['trades.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trade_pairs_strategy_open', 'trade_pairs', ['strategy_id', 'is_open'], unique=False)
    op.create_index(op.f('ix_trade_pairs_entry_time'), 'trade_pairs', ['entry_time'], unique=False)
    op.create_index(op.f('ix_trade_pairs_entry_trade_id'), 'trade_pairs', ['entry_trade_id'], unique=False)
    op.create_index(op.f('ix_trade_pairs_is_open'), 'trade_pairs', ['is_open'], unique=False)
    op.create_index(op.f('ix_trade_pairs_strategy_id'), 'trade_pairs', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_trade_pairs_user_id'), 'trade_pairs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_pairs_user_id'), table_name='trade_pairs')
    op.drop_index(op.f('ix_trade_pairs_strategy_id'), table_name='trade_pairs')
    op.drop_index(op.f('ix_trade_pairs_is_open'), table_name='trade_pairs')
    op.drop_index(op.f('ix_trade_pairs_entry_trade_id'), table_name='trade_pairs')
    op.drop_index(op.f('ix_trade_pairs_entry_time'), table_name='trade_pairs')
    op.drop_index('idx_trade_pairs_strategy_open', table_name='trade_pairs')
    op.drop_table('trade_pairs')
    op.drop_index(op.f('ix_trades_user_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_timestamp'), table_name='trades')
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_index(op.f('ix_trades_strategy_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_status'), table_name='trades')
    op.drop_index(op.f('ix_trades_position_side'), table_name='trades')
    op.drop_index(op.f('ix_trades_order_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_exit_reason'), table_name='trades')
    op.drop_index(op.f('ix_trades_created_at'), table_name='trades')
    op.drop_index('idx_trades_user_timestamp', table_name='trades', postgresql_ops={'timestamp': 'DESC'})
    op.drop_index('idx_trades_strategy_timestamp', table_name='trades', postgresql_ops={'timestamp': 'DESC'})
    op.drop_index('idx_trades_strategy_order_id', table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_system_events_strategy_id'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_event_type'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_event_level'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_created_at'), table_name='system_events')
    op.drop_table('system_events')
    op.drop_index(op.f('ix_strategy_metrics_strategy_id'), table_name='strategy_metrics')
    op.drop_index(op.f('ix_strategy_metrics_period_type'), table_name='strategy_metrics')
    op.drop_index('idx_strategy_metrics_period_type', table_name='strategy_metrics', postgresql_ops={'period_start': 'DESC'})
    op.drop_index('idx_strategy_metrics_period', table_name='strategy_metrics')
    op.drop_table('strategy_metrics')
    op.drop_index(op.f('ix_strategies_user_id'), table_name='strategies')
    op.drop_index(op.f('ix_strategies_symbol'), table_name='strategies')
    op.drop_index(op.f('ix_strategies_strategy_type'), table_name='strategies')
    op.drop_index(op.f('ix_strategies_strategy_id'), table_name='strategies')
    op.drop_index(op.f('ix_strategies_status'), table_name='strategies')
    op.drop_index(op.f('ix_strategies_position_side'), table_name='strategies')
    op.drop_index(op.f('ix_strategies_created_at'), table_name='strategies')
    op.drop_index(op.f('ix_strategies_account_id'), table_name='strategies')
    op.drop_index('idx_strategies_user_strategy_id', table_name='strategies')
    op.drop_index('idx_strategies_params', table_name='strategies', postgresql_using='gin')
    op.drop_table('strategies')
    op.drop_index(op.f('ix_backtest_trades_is_open'), table_name='backtest_trades')
    op.drop_index(op.f('ix_backtest_trades_entry_time'), table_name='backtest_trades')
    op.drop_index(op.f('ix_backtest_trades_backtest_id'), table_name='backtest_trades')
    op.drop_table('backtest_trades')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_session_token'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_is_active'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_expires_at'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_created_at'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index('idx_user_roles_user_id', table_name='user_roles')
    op.drop_index('idx_user_roles_role_id', table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_backtests_user_id'), table_name='backtests')
    op.drop_index(op.f('ix_backtests_symbol'), table_name='backtests')
    op.drop_index(op.f('ix_backtests_strategy_type'), table_name='backtests')
    op.drop_index(op.f('ix_backtests_start_time'), table_name='backtests')
    op.drop_index(op.f('ix_backtests_created_at'), table_name='backtests')
    op.drop_index('idx_backtests_params', table_name='backtests', postgresql_using='gin')
    op.drop_table('backtests')
    op.drop_index(op.f('ix_api_tokens_user_id'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_token_hash'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_is_active'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_expires_at'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_created_at'), table_name='api_tokens')
    op.drop_table('api_tokens')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_is_active'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_account_id'), table_name='accounts')
    op.drop_index('idx_accounts_user_account_id', table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###

