"""add_risk_management_tables

Revision ID: b08a3fc21d8f
Revises: a1b2c3d4e5f6
Create Date: 2026-01-05 23:56:12.788506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b08a3fc21d8f'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_management_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('max_portfolio_exposure_usdt', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('max_portfolio_exposure_pct', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('max_daily_loss_usdt', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('max_daily_loss_pct', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('max_weekly_loss_usdt', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('max_weekly_loss_pct', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('max_drawdown_pct', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('daily_loss_reset_time', sa.DateTime(), nullable=True),
    sa.Column('weekly_loss_reset_day', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('circuit_breaker_enabled', sa.Boolean(), nullable=False),
    sa.Column('max_consecutive_losses', sa.Integer(), nullable=False),
    sa.Column('rapid_loss_threshold_pct', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('rapid_loss_timeframe_minutes', sa.Integer(), nullable=False),
    sa.Column('circuit_breaker_cooldown_minutes', sa.Integer(), nullable=False),
    sa.Column('volatility_based_sizing_enabled', sa.Boolean(), nullable=False),
    sa.Column('performance_based_adjustment_enabled', sa.Boolean(), nullable=False),
    sa.Column('kelly_criterion_enabled', sa.Boolean(), nullable=False),
    sa.Column('kelly_fraction', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('correlation_limits_enabled', sa.Boolean(), nullable=False),
    sa.Column('max_correlation_exposure_pct', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('margin_call_protection_enabled', sa.Boolean(), nullable=False),
    sa.Column('min_margin_ratio', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('max_trades_per_day_per_strategy', sa.Integer(), nullable=True),
    sa.Column('max_trades_per_day_total', sa.Integer(), nullable=True),
    sa.Column('auto_reduce_order_size', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_risk_config_user_account_unique', 'risk_management_config', ['user_id', 'account_id'], unique=True)
    op.create_index(op.f('ix_risk_management_config_account_id'), 'risk_management_config', ['account_id'], unique=False)
    op.create_index(op.f('ix_risk_management_config_user_id'), 'risk_management_config', ['user_id'], unique=False)
    op.create_table('risk_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('total_balance_usdt', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('available_balance_usdt', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('used_margin_usdt', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('peak_balance_usdt', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('peak_balance_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_exposure_usdt', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('total_exposure_pct', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('daily_pnl_usdt', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('daily_pnl_pct', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('weekly_pnl_usdt', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('weekly_pnl_pct', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('current_drawdown_pct', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('max_drawdown_pct', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('profit_factor', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('win_rate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('avg_win', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('avg_loss', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('risk_status', sa.String(length=20), nullable=True),
    sa.Column('active_circuit_breakers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_risk_metrics_account_timestamp', 'risk_metrics', ['account_id', 'timestamp'], unique=False)
    op.create_index('idx_risk_metrics_user_timestamp', 'risk_metrics', ['user_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_risk_metrics_account_id'), 'risk_metrics', ['account_id'], unique=False)
    op.create_index(op.f('ix_risk_metrics_timestamp'), 'risk_metrics', ['timestamp'], unique=False)
    op.create_index(op.f('ix_risk_metrics_user_id'), 'risk_metrics', ['user_id'], unique=False)
    op.create_table('circuit_breaker_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=True),
    sa.Column('breaker_type', sa.String(length=50), nullable=False),
    sa.Column('breaker_scope', sa.String(length=20), nullable=False),
    sa.Column('trigger_value', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('threshold_value', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_circuit_breaker_account_status', 'circuit_breaker_events', ['account_id', 'status'], unique=False)
    op.create_index('idx_circuit_breaker_strategy_status', 'circuit_breaker_events', ['strategy_id', 'status'], unique=False)
    op.create_index(op.f('ix_circuit_breaker_events_account_id'), 'circuit_breaker_events', ['account_id'], unique=False)
    op.create_index(op.f('ix_circuit_breaker_events_strategy_id'), 'circuit_breaker_events', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_circuit_breaker_events_user_id'), 'circuit_breaker_events', ['user_id'], unique=False)
    op.drop_index(op.f('idx_accounts_exchange_platform'), table_name='accounts')
    op.create_index(op.f('ix_accounts_exchange_platform'), 'accounts', ['exchange_platform'], unique=False)
    op.create_index(op.f('ix_sensitivity_analyses_created_at'), 'sensitivity_analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_sensitivity_analyses_strategy_type'), 'sensitivity_analyses', ['strategy_type'], unique=False)
    op.create_index(op.f('ix_sensitivity_analyses_symbol'), 'sensitivity_analyses', ['symbol'], unique=False)
    op.create_index(op.f('ix_sensitivity_analyses_user_id'), 'sensitivity_analyses', ['user_id'], unique=False)
    op.create_index(op.f('ix_sensitivity_parameter_results_analysis_id'), 'sensitivity_parameter_results', ['analysis_id'], unique=False)
    op.drop_index(op.f('idx_strategies_auto_tuning_enabled'), table_name='strategies')
    op.create_index(op.f('ix_strategies_auto_tuning_enabled'), 'strategies', ['auto_tuning_enabled'], unique=False)
    op.drop_index(op.f('idx_strategy_metrics_period_type'), table_name='strategy_metrics')
    op.create_index('idx_strategy_metrics_period_type', 'strategy_metrics', ['period_type', 'period_start'], unique=False, postgresql_ops={'period_start': 'DESC'})
    op.drop_constraint(op.f('strategy_parameter_history_rollback_of_history_id_fkey'), 'strategy_parameter_history', type_='foreignkey')
    op.create_foreign_key(None, 'strategy_parameter_history', 'strategy_parameter_history', ['rollback_of_history_id'], ['id'])
    op.drop_index(op.f('idx_trades_strategy_timestamp'), table_name='trades')
    op.create_index('idx_trades_strategy_timestamp', 'trades', ['strategy_id', 'timestamp'], unique=False, postgresql_ops={'timestamp': 'DESC'})
    op.drop_index(op.f('idx_trades_user_timestamp'), table_name='trades')
    op.create_index('idx_trades_user_timestamp', 'trades', ['user_id', 'timestamp'], unique=False, postgresql_ops={'timestamp': 'DESC'})
    op.drop_index(op.f('idx_wf_analyses_created_at'), table_name='walk_forward_analyses')
    op.create_index('idx_wf_analyses_created_at', 'walk_forward_analyses', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    
    # Update strategies status constraint to include 'paused_by_risk'
    op.drop_constraint('strategies_status_check', 'strategies', type_='check')
    op.create_check_constraint(
        'strategies_status_check',
        'strategies',
        "status IN ('stopped', 'running', 'error', 'paused_by_risk')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_wf_analyses_created_at', table_name='walk_forward_analyses', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_wf_analyses_created_at'), 'walk_forward_analyses', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index('idx_trades_user_timestamp', table_name='trades', postgresql_ops={'timestamp': 'DESC'})
    op.create_index(op.f('idx_trades_user_timestamp'), 'trades', ['user_id', sa.literal_column('timestamp DESC')], unique=False)
    op.drop_index('idx_trades_strategy_timestamp', table_name='trades', postgresql_ops={'timestamp': 'DESC'})
    op.create_index(op.f('idx_trades_strategy_timestamp'), 'trades', ['strategy_id', sa.literal_column('timestamp DESC')], unique=False)
    op.drop_constraint(None, 'strategy_parameter_history', type_='foreignkey')
    op.create_foreign_key(op.f('strategy_parameter_history_rollback_of_history_id_fkey'), 'strategy_parameter_history', 'strategy_parameter_history', ['rollback_of_history_id'], ['id'], ondelete='SET NULL')
    op.drop_index('idx_strategy_metrics_period_type', table_name='strategy_metrics', postgresql_ops={'period_start': 'DESC'})
    op.create_index(op.f('idx_strategy_metrics_period_type'), 'strategy_metrics', ['period_type', sa.literal_column('period_start DESC')], unique=False)
    op.drop_index(op.f('ix_strategies_auto_tuning_enabled'), table_name='strategies')
    op.create_index(op.f('idx_strategies_auto_tuning_enabled'), 'strategies', ['auto_tuning_enabled'], unique=False)
    op.drop_index(op.f('ix_sensitivity_parameter_results_analysis_id'), table_name='sensitivity_parameter_results')
    op.drop_index(op.f('ix_sensitivity_analyses_user_id'), table_name='sensitivity_analyses')
    op.drop_index(op.f('ix_sensitivity_analyses_symbol'), table_name='sensitivity_analyses')
    op.drop_index(op.f('ix_sensitivity_analyses_strategy_type'), table_name='sensitivity_analyses')
    op.drop_index(op.f('ix_sensitivity_analyses_created_at'), table_name='sensitivity_analyses')
    # Revert strategies status constraint
    op.drop_constraint('strategies_status_check', 'strategies', type_='check')
    op.create_check_constraint(
        'strategies_status_check',
        'strategies',
        "status IN ('stopped', 'running', 'error')"
    )
    op.drop_index(op.f('ix_accounts_exchange_platform'), table_name='accounts')
    op.create_index(op.f('idx_accounts_exchange_platform'), 'accounts', ['exchange_platform'], unique=False)
    op.drop_index(op.f('ix_circuit_breaker_events_user_id'), table_name='circuit_breaker_events')
    op.drop_index(op.f('ix_circuit_breaker_events_strategy_id'), table_name='circuit_breaker_events')
    op.drop_index(op.f('ix_circuit_breaker_events_account_id'), table_name='circuit_breaker_events')
    op.drop_index('idx_circuit_breaker_strategy_status', table_name='circuit_breaker_events')
    op.drop_index('idx_circuit_breaker_account_status', table_name='circuit_breaker_events')
    op.drop_table('circuit_breaker_events')
    op.drop_index(op.f('ix_risk_metrics_user_id'), table_name='risk_metrics')
    op.drop_index(op.f('ix_risk_metrics_timestamp'), table_name='risk_metrics')
    op.drop_index(op.f('ix_risk_metrics_account_id'), table_name='risk_metrics')
    op.drop_index('idx_risk_metrics_user_timestamp', table_name='risk_metrics')
    op.drop_index('idx_risk_metrics_account_timestamp', table_name='risk_metrics')
    op.drop_table('risk_metrics')
    op.drop_index(op.f('ix_risk_management_config_user_id'), table_name='risk_management_config')
    op.drop_index(op.f('ix_risk_management_config_account_id'), table_name='risk_management_config')
    op.drop_index('idx_risk_config_user_account_unique', table_name='risk_management_config')
    op.drop_table('risk_management_config')
    # ### end Alembic commands ###

