"""add_risk_management_tables

Revision ID: b08a3fc21d8f
Revises: a1b2c3d4e5f6
Create Date: 2026-01-05 23:56:12.788506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b08a3fc21d8f'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Make migration idempotent: check for existing objects BEFORE creating them
    # This prevents transaction abort errors in PostgreSQL
    from sqlalchemy import inspect, text
    
    bind = op.get_bind()
    inspector = inspect(bind)
    
    # Get existing tables and indexes FIRST (before any operations that might fail)
    existing_tables = inspector.get_table_names()
    
    # Helper to get indexes for a table (returns empty list if table doesn't exist)
    def get_table_indexes(table_name):
        if table_name not in existing_tables:
            return []
        try:
            return [idx['name'] for idx in inspector.get_indexes(table_name)]
        except Exception:
            return []
    
    # Create risk_management_config table if it doesn't exist
    if 'risk_management_config' not in existing_tables:
        op.create_table('risk_management_config',
        sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('max_portfolio_exposure_usdt', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('max_portfolio_exposure_pct', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('max_daily_loss_usdt', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('max_daily_loss_pct', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('max_weekly_loss_usdt', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('max_weekly_loss_pct', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('max_drawdown_pct', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('daily_loss_reset_time', sa.DateTime(), nullable=True),
    sa.Column('weekly_loss_reset_day', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('circuit_breaker_enabled', sa.Boolean(), nullable=False),
    sa.Column('max_consecutive_losses', sa.Integer(), nullable=False),
    sa.Column('rapid_loss_threshold_pct', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('rapid_loss_timeframe_minutes', sa.Integer(), nullable=False),
    sa.Column('circuit_breaker_cooldown_minutes', sa.Integer(), nullable=False),
    sa.Column('volatility_based_sizing_enabled', sa.Boolean(), nullable=False),
    sa.Column('performance_based_adjustment_enabled', sa.Boolean(), nullable=False),
    sa.Column('kelly_criterion_enabled', sa.Boolean(), nullable=False),
    sa.Column('kelly_fraction', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('correlation_limits_enabled', sa.Boolean(), nullable=False),
    sa.Column('max_correlation_exposure_pct', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('margin_call_protection_enabled', sa.Boolean(), nullable=False),
    sa.Column('min_margin_ratio', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('max_trades_per_day_per_strategy', sa.Integer(), nullable=True),
    sa.Column('max_trades_per_day_total', sa.Integer(), nullable=True),
    sa.Column('auto_reduce_order_size', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
        risk_config_indexes = get_table_indexes('risk_management_config')
        if 'idx_risk_config_user_account_unique' not in risk_config_indexes:
            op.create_index('idx_risk_config_user_account_unique', 'risk_management_config', ['user_id', 'account_id'], unique=True)
        if 'ix_risk_management_config_account_id' not in risk_config_indexes:
            op.create_index(op.f('ix_risk_management_config_account_id'), 'risk_management_config', ['account_id'], unique=False)
        if 'ix_risk_management_config_user_id' not in risk_config_indexes:
            op.create_index(op.f('ix_risk_management_config_user_id'), 'risk_management_config', ['user_id'], unique=False)
    
    # Create risk_metrics table if it doesn't exist
    if 'risk_metrics' not in existing_tables:
        op.create_table('risk_metrics',
        sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('total_balance_usdt', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('available_balance_usdt', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('used_margin_usdt', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('peak_balance_usdt', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('peak_balance_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_exposure_usdt', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('total_exposure_pct', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('daily_pnl_usdt', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('daily_pnl_pct', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('weekly_pnl_usdt', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('weekly_pnl_pct', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('current_drawdown_pct', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('max_drawdown_pct', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('profit_factor', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('win_rate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('avg_win', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('avg_loss', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('risk_status', sa.String(length=20), nullable=True),
    sa.Column('active_circuit_breakers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
        risk_metrics_indexes = get_table_indexes('risk_metrics')
        if 'idx_risk_metrics_account_timestamp' not in risk_metrics_indexes:
            op.create_index('idx_risk_metrics_account_timestamp', 'risk_metrics', ['account_id', 'timestamp'], unique=False)
        if 'idx_risk_metrics_user_timestamp' not in risk_metrics_indexes:
            op.create_index('idx_risk_metrics_user_timestamp', 'risk_metrics', ['user_id', 'timestamp'], unique=False)
        if 'ix_risk_metrics_account_id' not in risk_metrics_indexes:
            op.create_index(op.f('ix_risk_metrics_account_id'), 'risk_metrics', ['account_id'], unique=False)
        if 'ix_risk_metrics_timestamp' not in risk_metrics_indexes:
            op.create_index(op.f('ix_risk_metrics_timestamp'), 'risk_metrics', ['timestamp'], unique=False)
        if 'ix_risk_metrics_user_id' not in risk_metrics_indexes:
            op.create_index(op.f('ix_risk_metrics_user_id'), 'risk_metrics', ['user_id'], unique=False)
    
    # Create circuit_breaker_events table if it doesn't exist
    if 'circuit_breaker_events' not in existing_tables:
        op.create_table('circuit_breaker_events',
        sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=True),
    sa.Column('breaker_type', sa.String(length=50), nullable=False),
    sa.Column('breaker_scope', sa.String(length=20), nullable=False),
    sa.Column('trigger_value', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('threshold_value', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
        circuit_breaker_indexes = get_table_indexes('circuit_breaker_events')
        if 'idx_circuit_breaker_account_status' not in circuit_breaker_indexes:
            op.create_index('idx_circuit_breaker_account_status', 'circuit_breaker_events', ['account_id', 'status'], unique=False)
        if 'idx_circuit_breaker_strategy_status' not in circuit_breaker_indexes:
            op.create_index('idx_circuit_breaker_strategy_status', 'circuit_breaker_events', ['strategy_id', 'status'], unique=False)
        if 'ix_circuit_breaker_events_account_id' not in circuit_breaker_indexes:
            op.create_index(op.f('ix_circuit_breaker_events_account_id'), 'circuit_breaker_events', ['account_id'], unique=False)
        if 'ix_circuit_breaker_events_strategy_id' not in circuit_breaker_indexes:
            op.create_index(op.f('ix_circuit_breaker_events_strategy_id'), 'circuit_breaker_events', ['strategy_id'], unique=False)
        if 'ix_circuit_breaker_events_user_id' not in circuit_breaker_indexes:
            op.create_index(op.f('ix_circuit_breaker_events_user_id'), 'circuit_breaker_events', ['user_id'], unique=False)
    
    # Handle indexes and constraints that may already exist (idempotent operations)
    # Check if index exists before dropping (it may not exist in some database states)
    indexes = [idx['name'] for idx in inspector.get_indexes('accounts')]
    if 'idx_accounts_exchange_platform' in indexes:
        op.drop_index(op.f('idx_accounts_exchange_platform'), table_name='accounts')
    
    # Create index only if it doesn't exist
    accounts_indexes = get_table_indexes('accounts')
    if 'idx_accounts_exchange_platform' in accounts_indexes:
        op.drop_index(op.f('idx_accounts_exchange_platform'), table_name='accounts')
    if 'ix_accounts_exchange_platform' not in accounts_indexes:
        op.create_index(op.f('ix_accounts_exchange_platform'), 'accounts', ['exchange_platform'], unique=False)
    
    # Create indexes only if they don't exist (idempotent)
    sensitivity_indexes = get_table_indexes('sensitivity_analyses')
    if 'ix_sensitivity_analyses_created_at' not in sensitivity_indexes:
        op.create_index(op.f('ix_sensitivity_analyses_created_at'), 'sensitivity_analyses', ['created_at'], unique=False)
    if 'ix_sensitivity_analyses_strategy_type' not in sensitivity_indexes:
        op.create_index(op.f('ix_sensitivity_analyses_strategy_type'), 'sensitivity_analyses', ['strategy_type'], unique=False)
    if 'ix_sensitivity_analyses_symbol' not in sensitivity_indexes:
        op.create_index(op.f('ix_sensitivity_analyses_symbol'), 'sensitivity_analyses', ['symbol'], unique=False)
    if 'ix_sensitivity_analyses_user_id' not in sensitivity_indexes:
        op.create_index(op.f('ix_sensitivity_analyses_user_id'), 'sensitivity_analyses', ['user_id'], unique=False)
    
    sensitivity_param_indexes = get_table_indexes('sensitivity_parameter_results')
    if 'ix_sensitivity_parameter_results_analysis_id' not in sensitivity_param_indexes:
        op.create_index(op.f('ix_sensitivity_parameter_results_analysis_id'), 'sensitivity_parameter_results', ['analysis_id'], unique=False)
    
    strategies_indexes = get_table_indexes('strategies')
    if 'idx_strategies_auto_tuning_enabled' in strategies_indexes:
        op.drop_index(op.f('idx_strategies_auto_tuning_enabled'), table_name='strategies')
    if 'ix_strategies_auto_tuning_enabled' not in strategies_indexes:
        op.create_index(op.f('ix_strategies_auto_tuning_enabled'), 'strategies', ['auto_tuning_enabled'], unique=False)
    
    strategy_metrics_indexes = get_table_indexes('strategy_metrics')
    if 'idx_strategy_metrics_period_type' in strategy_metrics_indexes:
        op.drop_index(op.f('idx_strategy_metrics_period_type'), table_name='strategy_metrics')
    if 'idx_strategy_metrics_period_type' not in strategy_metrics_indexes:
        op.create_index('idx_strategy_metrics_period_type', 'strategy_metrics', ['period_type', 'period_start'], unique=False, postgresql_ops={'period_start': 'DESC'})
    
    # Handle foreign key constraint (check if it exists first)
    if 'strategy_parameter_history' in existing_tables:
        try:
            fk_constraints = [fk['name'] for fk in inspector.get_foreign_keys('strategy_parameter_history') 
                              if 'rollback_of_history_id' in [col['name'] for col in fk.get('constrained_columns', [])]]
            if fk_constraints:
                op.drop_constraint(fk_constraints[0], 'strategy_parameter_history', type_='foreignkey')
            op.create_foreign_key(None, 'strategy_parameter_history', 'strategy_parameter_history', ['rollback_of_history_id'], ['id'])
        except Exception:
            pass  # Constraint may already exist or table may not exist
    
    trades_indexes = get_table_indexes('trades')
    if 'idx_trades_strategy_timestamp' in trades_indexes:
        op.drop_index(op.f('idx_trades_strategy_timestamp'), table_name='trades')
    if 'idx_trades_strategy_timestamp' not in trades_indexes:
        op.create_index('idx_trades_strategy_timestamp', 'trades', ['strategy_id', 'timestamp'], unique=False, postgresql_ops={'timestamp': 'DESC'})
    if 'idx_trades_user_timestamp' in trades_indexes:
        op.drop_index(op.f('idx_trades_user_timestamp'), table_name='trades')
    if 'idx_trades_user_timestamp' not in trades_indexes:
        op.create_index('idx_trades_user_timestamp', 'trades', ['user_id', 'timestamp'], unique=False, postgresql_ops={'timestamp': 'DESC'})
    
    wf_indexes = get_table_indexes('walk_forward_analyses')
    if 'idx_wf_analyses_created_at' in wf_indexes:
        op.drop_index(op.f('idx_wf_analyses_created_at'), table_name='walk_forward_analyses')
    if 'idx_wf_analyses_created_at' not in wf_indexes:
        op.create_index('idx_wf_analyses_created_at', 'walk_forward_analyses', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    
    # Update strategies status constraint to include 'paused_by_risk'
    op.drop_constraint('strategies_status_check', 'strategies', type_='check')
    op.create_check_constraint(
        'strategies_status_check',
        'strategies',
        "status IN ('stopped', 'running', 'error', 'paused_by_risk')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_wf_analyses_created_at', table_name='walk_forward_analyses', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_wf_analyses_created_at'), 'walk_forward_analyses', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index('idx_trades_user_timestamp', table_name='trades', postgresql_ops={'timestamp': 'DESC'})
    op.create_index(op.f('idx_trades_user_timestamp'), 'trades', ['user_id', sa.literal_column('timestamp DESC')], unique=False)
    op.drop_index('idx_trades_strategy_timestamp', table_name='trades', postgresql_ops={'timestamp': 'DESC'})
    op.create_index(op.f('idx_trades_strategy_timestamp'), 'trades', ['strategy_id', sa.literal_column('timestamp DESC')], unique=False)
    # Drop the foreign key constraint by name (it was created with None in upgrade, but PostgreSQL auto-generates a name)
    # Try to find and drop the constraint that references rollback_of_history_id
    from sqlalchemy import inspect, text
    bind = op.get_bind()
    inspector = inspect(bind)
    fk_constraints = [fk['name'] for fk in inspector.get_foreign_keys('strategy_parameter_history') 
                      if 'rollback_of_history_id' in [col['name'] for col in fk.get('constrained_columns', [])]]
    if fk_constraints:
        op.drop_constraint(fk_constraints[0], 'strategy_parameter_history', type_='foreignkey')
    else:
        # Fallback: try to find constraint by querying information_schema
        result = bind.execute(text("""
            SELECT conname FROM pg_constraint 
            WHERE conrelid = 'strategy_parameter_history'::regclass 
            AND contype = 'f' 
            AND conkey::text LIKE '%rollback_of_history_id%'
            LIMIT 1;
        """))
        constraint_name = result.scalar()
        if constraint_name:
            op.drop_constraint(constraint_name, 'strategy_parameter_history', type_='foreignkey')
    op.create_foreign_key(op.f('strategy_parameter_history_rollback_of_history_id_fkey'), 'strategy_parameter_history', 'strategy_parameter_history', ['rollback_of_history_id'], ['id'], ondelete='SET NULL')
    op.drop_index('idx_strategy_metrics_period_type', table_name='strategy_metrics', postgresql_ops={'period_start': 'DESC'})
    op.create_index(op.f('idx_strategy_metrics_period_type'), 'strategy_metrics', ['period_type', sa.literal_column('period_start DESC')], unique=False)
    op.drop_index(op.f('ix_strategies_auto_tuning_enabled'), table_name='strategies')
    op.create_index(op.f('idx_strategies_auto_tuning_enabled'), 'strategies', ['auto_tuning_enabled'], unique=False)
    op.drop_index(op.f('ix_sensitivity_parameter_results_analysis_id'), table_name='sensitivity_parameter_results')
    op.drop_index(op.f('ix_sensitivity_analyses_user_id'), table_name='sensitivity_analyses')
    op.drop_index(op.f('ix_sensitivity_analyses_symbol'), table_name='sensitivity_analyses')
    op.drop_index(op.f('ix_sensitivity_analyses_strategy_type'), table_name='sensitivity_analyses')
    op.drop_index(op.f('ix_sensitivity_analyses_created_at'), table_name='sensitivity_analyses')
    # Revert strategies status constraint
    op.drop_constraint('strategies_status_check', 'strategies', type_='check')
    op.create_check_constraint(
        'strategies_status_check',
        'strategies',
        "status IN ('stopped', 'running', 'error')"
    )
    op.drop_index(op.f('ix_accounts_exchange_platform'), table_name='accounts')
    op.create_index(op.f('idx_accounts_exchange_platform'), 'accounts', ['exchange_platform'], unique=False)
    op.drop_index(op.f('ix_circuit_breaker_events_user_id'), table_name='circuit_breaker_events')
    op.drop_index(op.f('ix_circuit_breaker_events_strategy_id'), table_name='circuit_breaker_events')
    op.drop_index(op.f('ix_circuit_breaker_events_account_id'), table_name='circuit_breaker_events')
    op.drop_index('idx_circuit_breaker_strategy_status', table_name='circuit_breaker_events')
    op.drop_index('idx_circuit_breaker_account_status', table_name='circuit_breaker_events')
    op.drop_table('circuit_breaker_events')
    op.drop_index(op.f('ix_risk_metrics_user_id'), table_name='risk_metrics')
    op.drop_index(op.f('ix_risk_metrics_timestamp'), table_name='risk_metrics')
    op.drop_index(op.f('ix_risk_metrics_account_id'), table_name='risk_metrics')
    op.drop_index('idx_risk_metrics_user_timestamp', table_name='risk_metrics')
    op.drop_index('idx_risk_metrics_account_timestamp', table_name='risk_metrics')
    op.drop_table('risk_metrics')
    op.drop_index(op.f('ix_risk_management_config_user_id'), table_name='risk_management_config')
    op.drop_index(op.f('ix_risk_management_config_account_id'), table_name='risk_management_config')
    op.drop_index('idx_risk_config_user_account_unique', table_name='risk_management_config')
    op.drop_table('risk_management_config')
    # ### end Alembic commands ###

